name: deploy to edge device
author: Hyeseung Lee
description: Deploy source codes to edge device
inputs:
  hostname:
    description: hostname (multiple available)
    required: true  
  password:
    description: edge device password
    required: true
  otp:
    required: true
  code_name:
    description: code module name ex.vv-edge-setup
    required: true
  zipfilename:
    description: zip file name
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pandas,requests for api call
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt