name: test-process

on:
  workflow_call:
    inputs:
      deploy-target-device:
        description: "배포 대상이 되는 디바이스"
        required: true
        type: string


jobs:
  Split-target-device-into-array:
    name: make target device string array
    runs-on: self-hosted
#    outputs:
#      device_arr: ${{ steps.split.outputs.test }}
#    steps:
#      - id: split
#      - run: IFS=','; DeviceArr=(${{inputs.deploy-target-device}}); unset IFS; echo
    steps:
      - name: Checkout the deploy-target repository
        uses: actions/checkout@v2

      - name: Checkout the action repository
        uses: actions/checkout@v2
        with:
          repository: teamdable/vv-deploy-actions
          path: action/

      - name: Get VPN IP of deploy-target devices
        run: |
          action/get-vpn-ip --allow-device ${{ inputs.deploy-target-device }}